language: ruby

rvm:
  - 2.6.1
  - 2.5.3
  - 2.4.5
  - 2.3.8
  - jruby-9.2.5.0
  - jruby-9.1.2.0
  - ruby-head
  - jruby-head

gemfile:
  - gemfiles/rack_1.x.gemfile
  - gemfiles/rack_2.gemfile

bundler_args: --path vendor/bundle

sudo: false

before_script:
  - bundle exec rake travis:before -t

script: bundle exec rake travis

after_script:
  - bundle exec rake travis:after -t

env:
  - - RUBYOPT=-W0
    - BUNDLE_WITHOUT=local_development

before_install:
  - bundle config --local without local_development

matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
  fast_finish: true

notifications:
  email:
    on_success: change
    on_failure: always
